import { describe, expect, afterAll, beforeAll, it } from '@jest/globals';
import request from 'supertest';
import dotenv from 'dotenv';

import { GlobalRole, User, ProjectRole, Ticket, Comment } from '@prisma/client';
import { app } from '../../src/app';
import path from 'path';
import fs from 'fs/promises';
import { prismaTest } from '../../src/lib/prismaTestClient';

import { resetTestDatabase } from '../../src/utilities/testUtilities/resetTestDatabase';
import { createUserProfile } from '../../src/utilities/testUtilities/createUserProfile';
import { createProject } from '../../src/utilities/testUtilities/createProject';
import { createBoard } from '../../src/utilities/testUtilities/createBoard';
import { createTicket } from '../../src/utilities/testUtilities/createTicket';
import { createComment } from '../../src/utilities/testUtilities/createComment';
import { createProjectMember } from '../../src/utilities/testUtilities/createProjectMember';
import { generateJwtToken } from '../../src/utilities/testUtilities/generateJwtToken';

dotenv.config();

describe('handleSingleUpload', () => {
  const testDescription = 'handleSingleUpload';
  let uploadedFileName1: string;
  let uploadedFileName2: string;
  let user1: User;
  let user2: User;
  let token: string;
  let ticket: Ticket | undefined;
  let comment: Comment;
  let comment2: Comment;

  beforeAll(async () => {
    await prismaTest.$connect();
    await resetTestDatabase();
    user1 = await createUserProfile(
      prismaTest,
      `${testDescription}_user1`,
      GlobalRole.USER
    );
    user2 = await createUserProfile(
      prismaTest,
      `${testDescription}_user2`,
      GlobalRole.USER
    );
    token = generateJwtToken(user1.id, user1.globalRole);
    const project = await createProject(prismaTest, testDescription, user1.id);
    const board = await createBoard(prismaTest, testDescription, project.id);
    ticket = await createTicket(
      prismaTest,
      testDescription,
      board.id,
      user1.id
    );
    comment = await createComment(
      prismaTest,
      testDescription,
      ticket.id,
      user1.id
    );
    comment2 = await createComment(
      prismaTest,
      `${testDescription}_2`,
      ticket.id,
      user2.id
    );
    await createProjectMember(
      prismaTest,
      project.id,
      user1.id,
      ProjectRole.USER
    );
  });

  it('should upload a single attachment', async () => {
    const filePathUpload = path.join(
      __dirname,
      '../../src/utilities/testUtilities/__fixtures__/image1.jpg'
    );
    const res = await request(app)
      .post(`/api/attachments/single`)
      .set('Authorization', `Bearer ${token}`)
      .field('entityType', 'COMMENT')
      .field('entityId', comment.id)
      .attach('file', filePathUpload);
    expect(res.status).toBe(201);
    expect(res.body.message).toEqual('File uploaded successfully');
    expect(res.body.attachment).toMatchObject({
      entityType: expect.any(String),
      entityId: expect.any(Number),
      uploadedBy: expect.any(Number),
      fileName: expect.any(String),
      fileType: expect.any(String),
      fileSize: expect.any(Number),
      storageType: expect.any(String),
    });
    expect(
      res.body.attachment.filePath === null ||
        typeof res.body.attachment.filePath === 'string'
    ).toBe(true);
    expect(
      res.body.attachment.fileUrl === null ||
        typeof res.body.attachment.fileUrl === 'string'
    ).toBe(true);
    uploadedFileName1 = res.body.attachment.filePath;
  });
  // Given the current architecture of the attachment routes, the attachment generated by this test will need to be manually removed. Post-MVP, the routes will be retooled to prevent the creation of attachments before authorization.
  it('should not allow the attachment to be attached', async () => {
    const filePathUpload = path.join(
      __dirname,
      '../../src/utilities/testUtilities/__fixtures__/image2.png'
    );
    const req = request(app)
      .post(`/api/attachments/single`)
      .set('Authorization', `Bearer ${token}`)
      .field('entityType', 'COMMENT')
      .field('entityId', comment2.id)
      .attach('file', filePathUpload);

    const res = await req;
    expect(res.status).toBe(401);
    expect(res.body.message).toBe('You do not own this comment');
    uploadedFileName2 = res.body.attachment;
  });
  afterAll(async () => {
    if (uploadedFileName1) {
      await fs.rm(uploadedFileName1, { force: true });
    }
    if (uploadedFileName2) {
      await fs.rm(uploadedFileName2, { force: true });
    }
    await prismaTest.$disconnect();
  });
});
